apiVersion: v1
kind: Secret
metadata:
    name: postgres-app-credentials
    namespace: data
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:HdUYUg==,iv:osfGDDmEO0MhjJ8DZZZps8eoCu18pJmGXdF/O+xKjFo=,tag:9SMx/T1NjM0xYwSgfe10Eg==,type:str]
    password: ENC[AES256_GCM,data:AFF7JFfYWMglczMxSBZJgmho,iv:7xgw1CGtkXoC9NdyYbs46+XbrxcNwk+A5v8NbyaoOjI=,tag:5LuPY/PQvE9xcW8JCeVS0A==,type:str]
sops:
    lastmodified: "2026-04-27T01:47:39Z"
    mac: ENC[AES256_GCM,data:rXTAONuCQBuRxq3C9I97oshrS7PsDVXaPNyXcplFQ1GMDYm2aeEco3DTi3cMkJ5vzKBW0FeBY1kQR3iIr8yc7DMuBQbsjL8BmABpBGcaTNu8qQTH3mvWiotKAK/Tkwo/aLJZosqjeNsVP4Cll/xuVUwU1YFHJ6KSr8wdkCCg0nE=,iv:dEUJzu2WO3OcBE32SeWu3tgex6U3ArfYWgWnvPAse3U=,tag:fZ3Xk4Wjf/HGkaaGrmS/HA==,type:str]
    pgp:
        - created_at: "2026-04-27T01:47:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOARAA5JWoAACpuV6mBH5e14UPBbxMt3x68uhbWg84VSgaydH3
            FFxIyk0aPcKWX7zb/b5fpsH+GpF5ZPeImAEwyzM66hsijSS6VCEIDFeiYQNgXQno
            CXmm6H0Ipxq2cOhNOSEniHn71fL5hB9Bup5nMAIh/GHHRT9pyXaNQfw15qnjdet0
            JDnbopNvsvEvRuMZ68q7NlkjnttpEUOywjpTpy4ALTaERxR1aEEg2JaSvxDKsce8
            Ly2LzXj57T4aKnHuCq1TPS0+iLRoOguGaIxf+u/qXt9p0XZ3P71YfNli5yjxq14H
            eQjpm12To8L1fFcltnAgm3KKb8NEcAM3Ho/wDWJ3o8nsFdxSmiCSCS/fnkyJyXsJ
            Pa3hhrUzGowLyanTfsbz7FoVJQBkFK/59loooqDKfW4CeaXFwJMcq5Pij1A0lwHb
            zO44DnUamyoqsjQtzpy1xY5ELs/7L7nBCwHQy1RzzdzWvobSLi0MYjxNviNWaXeQ
            kV37X4C6vtJ0ediZ9xrbu+eoPw26/iAuadoMYXbSn9thZmHA/28ZgufLb/0VavLz
            2czNxmuILW+m/aPzhfKy5tVI527X0CSyVphDcz45F3CGHIT+s7QwIbVZawlaC5px
            yqwCw1mA2CbmYEq5eLfItIKC5pPd4B4VlW+TCjDmEF6R5ETCahvykzRwGWjX5V/S
            XAFylOcfM7cltzIqwvpHLn5D32+UR/q2MZc/ERjLrK224y0Gkwz/6TJMxOwD2Okt
            9hUuFLzkfgatap1yRfagqVujTRvQRmzkY+k5AU7qGhlAIYPOne4thbjNF44e
            =11Gb
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser-secret
    namespace: data
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:D4jVX3Rc5ec=,iv:o5yw2t3+c8CJD0cmFtJKJwDW9Rb8wf9X9YOirUYiXDk=,tag:a+305s/CABDK7Xeg8lbPvw==,type:str]
    password: ENC[AES256_GCM,data:M+q0PPDhDfastDO4T/bZ,iv:ZAylurWKQXobPNtzZ+cw8KhqxKC65QqkNEaI3Isq6DA=,tag:9OFP/ptDVHTqJhC80uAJAA==,type:str]
sops:
    lastmodified: "2026-04-27T01:47:39Z"
    mac: ENC[AES256_GCM,data:rXTAONuCQBuRxq3C9I97oshrS7PsDVXaPNyXcplFQ1GMDYm2aeEco3DTi3cMkJ5vzKBW0FeBY1kQR3iIr8yc7DMuBQbsjL8BmABpBGcaTNu8qQTH3mvWiotKAK/Tkwo/aLJZosqjeNsVP4Cll/xuVUwU1YFHJ6KSr8wdkCCg0nE=,iv:dEUJzu2WO3OcBE32SeWu3tgex6U3ArfYWgWnvPAse3U=,tag:fZ3Xk4Wjf/HGkaaGrmS/HA==,type:str]
    pgp:
        - created_at: "2026-04-27T01:47:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOARAA5JWoAACpuV6mBH5e14UPBbxMt3x68uhbWg84VSgaydH3
            FFxIyk0aPcKWX7zb/b5fpsH+GpF5ZPeImAEwyzM66hsijSS6VCEIDFeiYQNgXQno
            CXmm6H0Ipxq2cOhNOSEniHn71fL5hB9Bup5nMAIh/GHHRT9pyXaNQfw15qnjdet0
            JDnbopNvsvEvRuMZ68q7NlkjnttpEUOywjpTpy4ALTaERxR1aEEg2JaSvxDKsce8
            Ly2LzXj57T4aKnHuCq1TPS0+iLRoOguGaIxf+u/qXt9p0XZ3P71YfNli5yjxq14H
            eQjpm12To8L1fFcltnAgm3KKb8NEcAM3Ho/wDWJ3o8nsFdxSmiCSCS/fnkyJyXsJ
            Pa3hhrUzGowLyanTfsbz7FoVJQBkFK/59loooqDKfW4CeaXFwJMcq5Pij1A0lwHb
            zO44DnUamyoqsjQtzpy1xY5ELs/7L7nBCwHQy1RzzdzWvobSLi0MYjxNviNWaXeQ
            kV37X4C6vtJ0ediZ9xrbu+eoPw26/iAuadoMYXbSn9thZmHA/28ZgufLb/0VavLz
            2czNxmuILW+m/aPzhfKy5tVI527X0CSyVphDcz45F3CGHIT+s7QwIbVZawlaC5px
            yqwCw1mA2CbmYEq5eLfItIKC5pPd4B4VlW+TCjDmEF6R5ETCahvykzRwGWjX5V/S
            XAFylOcfM7cltzIqwvpHLn5D32+UR/q2MZc/ERjLrK224y0Gkwz/6TJMxOwD2Okt
            9hUuFLzkfgatap1yRfagqVujTRvQRmzkY+k5AU7qGhlAIYPOne4thbjNF44e
            =11Gb
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
