apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:EOhAWB5kykJtt/2iTQbxL/M=,iv:M0YK8rlBFhzVeX1nIz/YvGg+0Cmk9Uhw7PqmKJ8NEGc=,tag:ovwT9UZa3ofKs2oJo7p30g==,type:str]
    client-secret: ENC[AES256_GCM,data:sXcbrDJQjms2bXrL4MIBctD5gqqZyRAo8e5Db60SdkVB/Q5x6qMDsocOjGdqYJJtkbI5Dfm4MM7PyLen5fJa,iv:rfXaENQc0hrWoM4MvJJEIGwMiRYpFQJczkIg0AELiok=,tag:Q0JjTB4pSjD1jW9yeG22DQ==,type:str]
sops:
    lastmodified: "2026-04-29T03:42:17Z"
    mac: ENC[AES256_GCM,data:NF/m6IWfYv0qdXBHlb/JliAkwbvlCxrBEIkErGWcZ3Z6Klis4Yx2+AE1kkem4cpIwo/AJzZiKXCbVgomgEZUHk0zJ80BiV3ZH/BDq/EMbGIEblHfKmrRo7SS8+ykUpUDh3qN/n83If2Znk1uW1Q7pmTCxlm9f4sFkdNj7Fb4hkE=,iv:1ZnhBiQl3HxKFxwStiGagS3ki7IoR2tgiS9xKIA3fQU=,tag:VI/vJ2vpGyx8vPCcTWtPfQ==,type:str]
    pgp:
        - created_at: "2026-04-29T03:42:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOAQ/6AxOL12b0oCYNIw7IDVNiDsmy014LzpH0bpVQAoFm+kgT
            IHQGWujjCanKkCjYPA8VRzN8SL5yLdlTFRxt5MiacoJwbJL5dAZvTeJX7ouhSgKf
            T6El3ZAnSaLqP1+PHu23gPL9mZ9rAW+pgg7je/RGy/6Myf1fM66HGlF5wx6L6n0+
            BAy5nIVnoxFch9VnPl9PvCeSYHSlKFKz8k3e2hj5njcOBsg6ilNRotYXi6uzUasO
            zC/hF+0o3/459tuzivWV+1KDSOLAY/qChGM8WWqmatmwTsactfYu8X/HtgFfLFVD
            KvIZ+ANT+dISAD52Cs/zO7EYFz5Te5sBsu6e3YS6edPhRkPbzIrXoNmNROCCIrY0
            i9f7D9xKywJ+zuDCQUxAv7s3XZA0eZvx8zHCN9Zxst/Ilr3V4mDH1dWrhwaPvzPz
            u5Og091jruGB+WhPJZZ3pikXqOgdluJ+7MqTpmgFV+QpQ+8y6VM7VmI+6ivOeY5B
            pRho+HxtodbuorQZTdlQPPwEDDJE9rhhaZogk7IRN7gebG60cZ8K1/jMhOiWt0rG
            pXCUhW1SUKK0jmGQi6YFgaj01K6o0U4EeF/clpRIS5zQSt0A+dcQ7xERiKJVsi9f
            xH7NYU1/PZvox68U43ndD7IyEV741yyHee7dOn67a+T3Cs2Ne+umAjfPThRVmeXS
            XgHBSePH+YSC+K0i7nlbVfUmSUYC/rJLLr6QmF00hCmfcnEIT9ypmTk8b5n1Ihc1
            ZoxNbQKhZ4Ygu57rTIpzY/u5sUfCebeaBeRc59GvoOH/HF9SKnIerXwAJalW+gY=
            =jOhI
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
