apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: '1.6.x'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 10m
      timeout: 15m
  values:
    replicaCount: 2
    storageMinimalAvailablePercentage: 10
    # Automatic salvage of volumes after node failure
    autoSalvage: true
    ingress:
      enabled: true
      host: longhorn.home
#    metrics:
#      serviceMonitor:
#        enabled: true
