apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgre-sql
  namespace: data
spec:
  instances: 3

  # PostgreSQL version
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1024MB"
      work_mem: "4MB"
      maintenance_work_mem: "64MB"

  superuserSecret:
    name: postgres-superuser-secret

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: postgres-app-credentials

  storage:
    size: 10Gi
    storageClass: longhorn-triple

  monitoring:
    enablePodMonitor: true
