apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dns-lb.yaml
  - coredns-configmap.yaml
patches:
  - path: coredns-config.yaml
    target:
      kind: ConfigMap
      name: coredns
      namespace: kube-system
