---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: '1.96.x'
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: tailscale-operator
        namespace: tailscale
  values:
    operatorConfig:
      hostname: "homelab-tailscale-operator"
    apiServerProxyConfig:
      mode: "true"
    oauth:
      clientId:
        secret:
          name: tailscale-auth
          key: client_id
      clientSecret:
        secret:
          name: tailscale-auth
          key: client_secret
